services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /root/redis/data:/data
    command: >
      redis-server
      --appendonly yes
      --requirepass lbs990129...
    networks:
      - redis-net
